---
abstract: 'Simple structured errors with full backtrace'
author:
  - 'Xiong Changnian <xiong@cpan.org>'
build_requires:
  Test::More: 0.94
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
keywords:
  - devel
  - development
  - error
  - errors
  - exception
  - exceptions
  - OO
  - object-oriented
  - class
  - object
  - method
  - carp
  - croak
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Error-Base
provides:
  Error::Base:
    file: lib/Error/Base.pm
    version: v0.1.4
  Error::Base::Cookbook:
    file: lib/Error/Base/Cookbook.pm
    version: v0.1.4
  Error::Base::Late:
    file: lib/Error/Base.pm
    version: 0
recommends:
  Devel::Comments: v1.1.4
  Test::Trap: v0.2.1
requires:
  Scalar::Util: 0
  overload: 0
  perl: 5.008008
  version: 0.94
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: http://github.com/Xiong/error-base
version: v0.1.4
